name: test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: lerna run test --since origin/main
        if: github.ref != 'refs/heads/main'
      - run: npm run test
        if: github.ref == 'refs/heads/main'
